In [61]:
import pandas as pd

In [62]:
df=pd.read_csv("https://raw.githubusercontent.com/krishnaik06/FSDSRegression/refs/heads/main/notebooks/data/gemstone.csv")

In [63]:
df

id  carat        cut color clarity  depth  table     x     y  \
0            0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33   
1            1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12   
2            2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73   
3            3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41   
4            4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61   
...        ...    ...        ...   ...     ...    ...    ...   ...   ...   
193568  193568   0.31      Ideal     D    VVS2   61.1   56.0  4.35  4.39   
193569  193569   0.70    Premium     G    VVS2   60.3   58.0  5.75  5.77   
193570  193570   0.73  Very Good     F     SI1   63.1   57.0  5.72  5.75   
193571  193571   0.34  Very Good     D     SI1   62.9   55.0  4.45  4.49   
193572  193572   0.71       Good     E     SI2   60.8   64.0  5.73  5.71   

           z  price  
0       4.55  13619  
1       5.05  13387  
2       3.50   2772  
3       2.71    666  
4       4.77  14453  
...      ...    ...  
193568  2.67   1130  
193569  3.47   2874  
193570  3.62   3036  
193571  2.81    681  
193572  3.48   2258  

[193573 rows x 11 columns]

In [64]:
df=df.drop(labels=['id'],axis=1)


In [65]:
## Independent and dependent features
X = df.drop(labels=['price'],axis=1)
Y = df[['price']]

In [66]:
# Define the custom ranking for each ordinal variable
cut_categories = ['Fair', 'Good', 'Very Good','Premium','Ideal']
color_categories = ['D', 'E', 'F', 'G', 'H', 'I', 'J']
clarity_categories = ['I1','SI2','SI1','VS2','VS1','VVS2','VVS1','IF']

In [67]:
from sklearn.impute import SimpleImputer ## HAndling Missing Values
from sklearn.preprocessing import StandardScaler # HAndling Feature Scaling
from sklearn.preprocessing import OrdinalEncoder # Ordinal Encoding
## pipelines
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [68]:
## Numerical Pipeline
num_pipeline=Pipeline(
    steps=[
    ('imputer',SimpleImputer(strategy='median')),
    ('scaler',StandardScaler())

    ]

)

# Categorigal Pipeline
cat_pipeline=Pipeline(
    steps=[
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('ordinalencoder',OrdinalEncoder(categories=[cut_categories,color_categories,clarity_categories])),
    ('scaler',StandardScaler())
    ]

)

preprocessor=ColumnTransformer([
('num_pipeline',num_pipeline,numerical_cols),
('cat_pipeline',cat_pipeline,categorical_cols)
])

In [69]:
## Train test split

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.30,random_state=30)

In [70]:
preprocessor.fit_transform(X_train)

array([[-0.97543926, -0.84960654, -0.12153081, ...,  0.87407553,
         1.52872212,  1.35273128],
       [ 0.2351953 ,  1.83363716, -0.12153081, ..., -2.14455824,
        -0.93507064, -0.64678628],
       [ 0.49461699,  0.81585507,  0.39980029, ..., -0.13213573,
         0.29682574,  0.68622543],
       ...,
       [ 0.45138004,  1.55606023, -0.6428619 , ..., -2.14455824,
         0.29682574, -0.64678628],
       [ 0.66756478, -1.77486298,  1.44246248, ...,  0.87407553,
         0.29682574,  0.68622543],
       [ 0.25681377,  0.81585507, -0.12153081, ...,  0.87407553,
         0.29682574, -0.64678628]])

In [71]:
X_train=pd.DataFrame(preprocessor.fit_transform(X_train),columns=preprocessor.get_feature_names_out())
X_test=pd.DataFrame(preprocessor.transform(X_test),columns=preprocessor.get_feature_names_out())

In [72]:
X_train

num_pipeline__carat  num_pipeline__depth  num_pipeline__table  \
0                 -0.975439            -0.849607            -0.121531   
1                  0.235195             1.833637            -0.121531   
2                  0.494617             0.815855             0.399800   
3                 -1.018676             0.260701             0.921131   
4                 -0.953821            -0.664555            -0.642862   
...                     ...                  ...                  ...   
135496            -1.040295            -0.016876            -0.642862   
135497             0.991842             0.168176            -0.642862   
135498             0.451380             1.556060            -0.642862   
135499             0.667565            -1.774863             1.442462   
135500             0.256814             0.815855            -0.121531   

        num_pipeline__x  num_pipeline__y  num_pipeline__z  cat_pipeline__cut  \
0             -1.042757        -1.080970        -1.123150           0.874076   
1              0.318447         0.279859         0.485354          -2.144558   
2              0.570855         0.606458         0.673737          -0.132136   
3             -1.214034        -1.244270        -1.195605          -0.132136   
4             -1.069801        -1.044681        -1.094168           0.874076   
...                 ...              ...              ...                ...   
135496        -1.268122        -1.244270        -1.239078           0.874076   
135497         1.048629         1.114501         1.079486           0.874076   
135498         0.516768         0.588314         0.702719          -2.144558   
135499         0.868337         0.951202         0.688228           0.874076   
135500         0.381549         0.415942         0.470863           0.874076   

        cat_pipeline__color  cat_pipeline__clarity  
0                  1.528722               1.352731  
1                 -0.935071              -0.646786  
2                  0.296826               0.686225  
3                  0.296826               0.019720  
4                  2.144670               1.352731  
...                     ...                    ...  
135496            -0.935071              -0.646786  
135497             0.296826              -1.313292  
135498             0.296826              -0.646786  
135499             0.296826               0.686225  
135500             0.296826              -0.646786  

[135501 rows x 9 columns]

In [73]:
## Model Training

from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [74]:
regression=LinearRegression()
regression.fit(X_train,y_train)

LinearRegression()

In [75]:
regression.coef_


array([[ 6433.66003594,  -132.75843566,   -70.42922179, -1720.30971463,
         -499.29302619,   -63.39317848,    72.44537247,  -460.41604642,
          650.76431652]])

In [76]:
regression.intercept_

array([3970.76628955])

In [77]:
import numpy as np
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [78]:
## Train multiple models

models={
    'LinearRegression':LinearRegression(),
    'Lasso':Lasso(),
    'Ridge':Ridge(),
    'Elasticnet':ElasticNet()
}
trained_model_list=[]
model_list=[]
r2_list=[]

for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)

    #Make Predictions
    y_pred=model.predict(X_test)

    mae, rmse, r2_square=evaluate_model(y_test,y_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print('Model Training Performance')
    print("RMSE:",rmse)
    print("MAE:",mae)
    print("R2 score",r2_square*100)

    r2_list.append(r2_square)

    print('='*35)
    print('\n')

LinearRegression
Model Training Performance
RMSE: 1013.9047094344002
MAE: 674.025511579685
R2 score 93.68908248567512


Lasso
Model Training Performance
RMSE: 1013.8784226767013
MAE: 675.0716923362156
R2 score 93.68940971841704


Ridge
Model Training Performance
RMSE: 1013.9059272771406
MAE: 674.0555800798531
R2 score 93.68906732505968


Elasticnet
Model Training Performance
RMSE: 1533.4162456064046
MAE: 1060.7368759154729
R2 score 85.56494831165182




In [79]:
model_list

['LinearRegression', 'Lasso', 'Ridge', 'Elasticnet']

In [80]:
r2_list

[0.9368908248567511,
 0.9368940971841704,
 0.9368906732505968,
 0.8556494831165182]